// <auto-generated />
namespace InvoiceApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MinorChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MinorChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201902200212287_Minor-Changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
